version: '3'

services:
  app:
    build: .
    image: "youtube:latest"
    container_name: "youtube"
    entrypoint: /usr/src/app/entrypoint.sh
    volumes:
      - ./staticfiles:/usr/src/app/staticfiles
    ports:
      - 8000:8000

  nginx:
    build: ./nginx
    container_name: "youtube_nginx"
    volumes:
      - ./staticfiles:/usr/src/app/staticfiles
    ports:
      - 80:80
    depends_on:
      - app